version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/rest/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  app:
    image: chat
    container_name: chat
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db